config/routes.rb
Rails.application.routes.draw do
  
  resources :manages
  resources :boxes
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'basic'    => 'static_pages#basic'
  get 'packages'    => 'static_pages#packages'
  get 'vault'    => 'static_pages#vault'
  get 'suggestions'    => 'static_pages#suggestions'
  get 'sample'    => 'static_pages#sample'
  get 'deleteaccount'    => 'static_pages#delete_account'
  get 'premium'    => 'static_pages#premium'
  get 'about'   => 'static_pages#about'
  get 'giftshop'   => 'static_pages#giftshop'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'invite'    => 'static_pages#invite'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boxes,          only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
  
  
  resources :relationships,       only: [:create, :destroy]
  resources :boxes do
  resources :microposts
    end
  
  resources :users do
  resources :microposts
    end
  resources :users do
  resources :boxes
    end
  resources :boxes do
  resources :users
    end
  resources :microposts do
  resources :users
    end
  resources :microposts do
  resources :boxes
    end
  
  resources :users,                only: [:edit, :create, :destroy]
  resources :boxes,                only: [:edit, :create, :destroy]
  resources :reverses
  resources :manages
  resources :microposts,          only: [:edit, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def youriepay
  end
  
  def about
  end
  
  def contact
  end
  
  def giftshop
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<title>About | Yourie</title>
<% provide(:title, "About") %>
<br />
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br>

<h1>About Yourie</h1><br />
<center><h3>It is said that a picture is worth a thousand words.</br> </br> 
It can also be said that behind every picture there is a </br>story that pictures alone cannot tell.</h3></center> </br>

<p>


<!--<<h4><center>Every life is filled with stories!-->

<center><h3>With Yourie you can create "Digital Books" to organize, store and share<br /> your memorable life experiences using pictures and text.<br /><br />
<br />
You can also use Yourie to store things like favorite recipes,<br />
build personal blogs and categorize essentially anything. <br /><br />
<br />
<h1>Sample Yourie Bookshelf</h1>
<%= image_tag("sampleindex.png", alt: "Family Bookshelf") %>
<br /><br />
<h1>Sample Yourie Book</h1>
<%= image_tag("shells 10th 1.png", alt: "Shells Bday") %><br /><br />
<br /><br />
<h1>Sample Yourie Recipe Book</h1>
<%= image_tag("recipes.png", alt: "Recipes") %><br /><br />
<h1>Share with Family & Friends</h1>
<%= image_tag("follow2.png", alt: "Follow") %><br /><br /></center>
</br></br>
<center><%= link_to "FREE BASIC", basic_path, class: "btn btn-lg btn-primary" %>&nbsp;&nbsp; <%= link_to "PREMIUM", premium_path, class: "btn btn-lg btn-primary" %></br></center>

</br>
<center>Photos Stored Safely on Amazon's AWS Storage Services <%=image_tag("Amazon.png", alt: "Amazon")%>
<%= link_to image_tag("cloud.png", alt: "Cloud logo"),
              'https://yourie.herokuapp.com/' %></br></center><br />
</p>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/basic.erb
<title>BASIC | Yourie</title>
<% provide(:title, "Yourie Basic") %>
<br />
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br></br>
              
<h1><a href="https://yourie.herokuapp.com/signup" title="FREE BASIC"><u>FREE BASIC!</u></a></h1>
<center><i>No Credit Card Required</i></center></br>

<center><p>
<h3>Your Basic Account Includes:</h3><br />


&#8226;  10 Books<br />
&#8226;  Unlimted Text Posts<br />
&#8226;  500 Photo Posts<br />
&#8226;  Unlimited Follow/Followed (Shares)<br />
&#8226;  10 Gigibites Storage*<br />

</br>
<i>* Additional storage can be purchased for $10 per year per 50 GB.</i>
<br /></center>
<br /><br />
<center> <%#= link_to "PREMIUM", premium_path, class: "btn btn-lg btn-primary" %></br></center>



<center>Photos Stored Safely on Amazon's AWS Storage Services <%=image_tag("Amazon.png", alt: "Amazon")%></center> 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/contact.html.erb
<% provide(:title, "Privacy Policy") %>
<h1>Privacy Policy</h1>
<p>
 <center><b>USDigiBrands</b></center>
</p>
      <p>This document was last updated on May 25, 2016.</p>
    <p>1. Acknowledgment and acceptance of terms</p>
    <p>USDigiBrands is committed to protecting your privacy.  This Privacy Statement sets forth our current privacy practices with regard to  the information we collect when you or your computer interact with our websites.   By  accessing USDigiBrands Website Addresses, you acknowledge and  fully understand USDigiBrands’s Privacy Statement and freely consent to  the information collection and use practices described in this Website Privacy Statement.</p>
    <p>2. Participating Merchant Policies </p>
    <p>Related services and offerings with links from this website,  including vendor sites, have their own privacy statements that can be viewed by  clicking on the corresponding links within each respective website. Online  merchants and others who participate in USDigiBrands services are  encouraged to participate in industry privacy initiatives and to take a  responsible attitude towards consumer privacy.   However, since we do not have direct control over the policies or  practices of participating merchants and other third parties, we are not  responsible for the privacy practices or contents of those sites.  We recommend and encourage that you always  review the privacy policies of merchants and other third parties before you  provide any personal information or complete any transaction with such parties.<br />
    </p>
    <p>3. Information We Collect and How We Use It </p>
    <br />
    USDigiBrands collects certain information from and about its users  three ways: directly from our Web Server logs, the user, and with Cookies.
  </p>
  <p>a. Web  Server Logs. </p>
  <p>When you visit our Websites, we may track  information to administer the site and analyze its usage. Examples of  information we may track include: </p>
  <ul type="disc">
    <li>Your Internet protocol address. </li>
    <li>The kind of browser or computer you use. </li>
    <li>Number of links you click within the site. </li>
    <li>State or country from which you accessed the site. </li>
    <li>Date and time of your visit. </li>
    <li>Name of your Internet service provider. </li>
    <li>Web page you linked to our site from. </li>
    <li>Pages you viewed on the site.</li>
  </ul>
  <p>b. Use of Cookies</p>
  <p>USDigiBrands may use cookies to personalize or enhance your user experience.  A cookie is a  small text file that is placed on your hard disk by a Web page server.  Cookies cannot be used to run programs or  deliver viruses to your computer.   Cookies are uniquely assigned to you, and can only be read by a Web  Server in the domain that issued the cookie to you.  </p>
  <p>One of the primary purposes of cookies is to provide a convenience feature to save you time.   For example, if you personalize a web page, or navigate within a site, a  cookie helps the site to recall your specific information on subsequent visits.  Hence, this simplifies the process of  delivering relevant content and eases site navigation by providing and saving  your preferences and login information as well as providing personalized  functionality..  </p>
  <p>USDigiBrands reserves the right to share aggregated site statistics with partner companies, but does not allow other companies to  place cookies on our website unless there is a temporary, overriding customer  value (such as merging into USDigiBrands sites that relies on third-party  cookies).</p>
  <p>You have the ability to accept or decline cookies.  Most Web browsers automatically accept  cookies, but you can usually modify your browser setting to decline cookies. If  you reject cookies by changing your browser settings then be aware that this may  disable some of the functionality on our Website.</p>
  <ul>
    <li>Google, as a third party vendor, uses cookies to serve ads on our sites. </li>
    <li>Google's use of the DART cookie enables it to serve ads to our users based on their visit to our sites and other sites on the Internet. </li>
    <li>Users may opt out of the use of the DART cookie by visiting the <a href="http://www.google.com/privacy_ads.html">Google ad and content network privacy policy</a>. </li>
  </ul>
  <p>c. Personal Information Users</p>
  <p>Visitors to our websites can register to purchase services and to participate in games and contests.   When you register, we will request some personal information such as  name, address, email, telephone number or facsimile number, account number and  other relevant information.  If you are  purchasing a service, we will request financial information.  Any financial information we collect is used  only to bill you for the services you purchased.  If you purchase by credit card, this  information may be forwarded to your credit card provider. For other types of  registrations, we will ask for the relevant information. You may also be asked  to disclose personal information to us so that we can provide assistance and  information to you. For example, such data may be warranted in order to provide  online technical support and troubleshooting.</p>
  <p>We will not disclose personally identifiable information we collect from you to third parties without your permission except to the extent  necessary including:</p>
  <ul>
    <li>To  fulfill your service requests for services.</li>
    <li>To  protect ourselves from liability,</li>
    <li>To  respond to legal process or comply with law, or</li>
    <li>In  connection with a merger, acquisition, or liquidation of the company.</li>
  </ul>
  <p>4. Use of Web Beacons or GIF files</p>
  <p>USDigiBrands Web pages may contain electronic images known as  Web beacons – sometimes also called single-pixel gifs – that allow USDigiBrands to count users who have visited those pages and to deliver  co-branded services.  USDigiBrands  may include Web beacons in promotional e-mail messages or newsletters in order  to determine whether messages have been opened and acted upon.</p>
  <p>Some of these Web beacons may be placed by third party  service providers to help determine the effectiveness of our advertising  campaigns or email communications.  These  Web beacons may be used by these service providers to place a persistent cookie  on your computer.  This allows the  service provider to recognize your computer each time you visit certain pages  or emails and compile anonymous information in relation to those page views,  which in turn enables us and our service providers to learn which  advertisements and emails bring you to our website and how you use the site.  USDigiBrands prohibits Web beacons from  being used to collect or access your personal information.</p>
  <p>5. Accessing Web Account Information</p>
  <p>We will provide you with the means to ensure that personally identifiable information in your web account file is correct and current.  You may review this information by contacting  us by sending an email to our support attendant --admin@yourie.com.</p>
  <p>6. Changes to this Statement</p>
  <p>USDigiBrands has the discretion to occasionally update  this privacy statement.  When we do, we  will also revise the “updated” date at the top of this Privacy page.  We encourage you to periodically review this  privacy statement to stay informed about how we are helping to protect the  personal information we collect.  Your  continued use of the service constitutes your agreement to this privacy  statement and any updates.</p>
  <p>7. Contacting Us </p>
  <p>If you have questions regarding our Privacy Statement, its implementation, failure to adhere to this Privacy Statement and/or our general practices, please contact us or send your comments to:</p>
  <p>admin@usdigibrands.com<br />
    Attention:  Privacy Statement Personnel</p>
  <p>USDigiBrands will use commercially reasonable efforts to promptly respond and resolve any problem or question.</p>

app/views/static_pages/delete_account.erb
<% @user = current_user %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for current_user %> </h1>
        <%= @user.name %>
     </section>
   </aside>
</div>
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br>
<h1>Cancel Your Yourie Account</h1></br>
<center><h1>We are sorry to see you go!</h1></center></br>
<center><b>To cancel your account: copy and paste the text in the box below into the body of an email and send to <u>admin@usdgb.com</u></b></br>
Once we recieve and verify your request we will cancel your account and delete all associated posts.
</br>
</br>
<i><b>CAUTION: The account and data cannot not be retrieved!!!</b></i>
</br>
</br>
<i>Do not refresh this page</i></center></br></br>

   <section class="box">
     <div class="col-md-6">
       <textarea rows="9"> 
  Please cancel my <%= @user.name %> Yourie Account and delete all associated posts.

  Account: <%= request.referrer %>

  I understand that the account and data cannot not be retrieved!!!
      </textarea>
    </div>
  </section>
  
<center><b>Once you are finished with the email, click Close.</br>

<%= link_to "Close", url_for(:back), class: "btn btn-sm btn-primary" %></b></center>

app/views/static_pages/home.html.erb
<!--views/static_pages/home.html.erb-->
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      
    </aside>
    </div>
    <script type="text/javascript">stLight.options({publisher: "c14ff29b-ab4b-400b-8636-5feeac74864c", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<script>
var options={ "publisher": "c14ff29b-ab4b-400b-8636-5feeac74864c", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "googleplus", "pinterest", "email", "sharethis"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>

    
  </br>
  <h1>Welcome Back!</h1>
    <center>
 
    <%= link_to image_tag("YourieLRG.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></br>

  
<%= link_to image_tag("cloud.png", alt: "Cloud logo"),
              'https://yourie.herokuapp.com/' %></br>
    </center>
    
<% else %>
</br>
  
  <center><h3><i><font color="#0099ff">Every Life Is A Story&trade;</font> </i></center>
  <div class="center">
       <%= link_to image_tag("YourieLRGDMB.png", alt: "Yourie logo"), 'http://www.yourie.com/' %>
  
 </div>
<script type="text/javascript">stLight.options({publisher: "c14ff29b-ab4b-400b-8636-5feeac74864c", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<script>
var options={ "publisher": "c14ff29b-ab4b-400b-8636-5feeac74864c", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "linkedin", "googleplus", "pinterest", "email", "sharethis"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>

<%#= link_to image_tag("Autumn 2.png", alt: "Yourie logo")%>
<%#= link_to image_tag("Autumn.png", alt: "Yourie logo")%>
<%#= link_to image_tag("Autumn 3.png", alt: "Yourie logo")%></cenetr></br></br>
<h4><center><!--A better way to organize, store and share your most treasured content.--> 
<center><h3><i><font color="#00008B">Organize, store and share your treasured memories with photos and stories! </i></center>
</br>
<center>&#8226; Free Up Your Smartphone Camera Roll</center></br>
<center>&#8226; Share Personal Stories and Experiences with Family & Friends</center></br>
<center>&#8226; Private - No Public Feeds</center></br>
<center>&#8226; No Ads</center></br>
<center>&#8226; Safe for Children</font></center></br><!-- <br /><br />
<!--   <h4><center>Create life  "Memory Books” using photos, text, videos, music,</br>and more and share them with your family and friends.-->
<!-- <br /><br />
  <a href="https://yourie.herokuapp.com/sample"target="_blank">Click here to see a Sample Yourie</a></h4></center>--></center>
</h4>  <br />
<center><%= link_to "FREE BASIC", basic_path, class: "btn btn-lg btn-primary" %>&nbsp;&nbsp; <%= link_to "PREMIUM", premium_path, class: "btn btn-lg btn-primary" %></br></center>

<center><%#= link_to image_tag("Free Basic.png"), signup_path %><%#= image_tag("Basic Plus.png") %><%#= image_tag("Plan Premium.png") %></center>
<center></br>
<h4>Great on Smart Phones, Tablets & PCs!</h4>

<%= image_tag("smart phone yourie.png") %>
              
<%= image_tag("Tablet.png") %>
              
<%= image_tag("pc yourie.jpg") %></center>
  
  <center><%#= link_to "View A Sample Yourie Album", 'https://yourie.herokuapp.com/users/pmvxzVQd', class: "btn btn-lg btn-primary" %></center>
  <!--</br></br><center>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Build Custom Bookshelves&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create Books&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Share them with Family & Friends&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</center>
<center><%#= image_tag("family booksm.png")%><%#= image_tag("weddingsm.png")%><%#= image_tag("shellsm.png")%></br>
</center></br></br>
<!-- <i> To to see a <b>"Sample"</b> Yourie </br>
  Create an account, login and click the About/Help tab.</i> </a></h1></center></br></br> --><br /><br /></center>
<center>Photos Stored Safely on Amazon's AWS Storage Services <%=image_tag("Amazon.png", alt: "Amazon")%>
<%= link_to image_tag("cloud.png", alt: "Cloud logo"),
              'https://yourie.herokuapp.com/' %></center></br><br />
  
  <% end %>
  <center>
<br />
<font color="#0099ff"> Be Sure To Visit Our Gift Shop For Great Holiday Gifts Ideas!</font><br />
<br /><br />
<%= link_to image_tag("youriemugmed.png", alt: "mug"),'https://yourie.herokuapp.com/giftshop'  %></center>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/invite.erb
<% @user = current_user %></br>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for current_user %> </h1>
        <%= @user.name %>
     </section>
   </aside>
</div>
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br>
<center><b>Invitate to A Friend or Family Member to view your Yourie Album!</br></br>
To send an invitation: copy and paste the text in the box below into the body of an email and send to your invitee.</b></br>
<i>Do not refresh this page</i></center></br></br>

   <section class="box">
     <div class="col-md-6">
       <textarea rows="15"> 

 I would like to share my Yourie Album with you!

 If you have a Yourie account click this link:

           <%=  request.referrer %>

 If you do not have a Yourie account, click the link below and sign up for a 
 new account and then come back to this email and click the link above.

           https://yourie.herokuapp.com/


      </textarea>
    </div>
  </section>
 
<center><b>Once you are finished with the email, click Close.</br>

<%= link_to "Close", url_for(:back), class: "btn btn-sm btn-primary" %></b></center>

app/views/static_pages/packages.erb
<title>Friends & Family | Yourie</title>
<% provide(:title, "Friends & Family") %>

<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br>
<h1>Gift Certificates!</h1>
<center>
<h2>Share all your treasured moments and memories with your friends and loved ones - and they can share theirs with you!  </br></br>

Order the number of certificates you would like and we will send them to you to sign and deliever. 
</br></br>Send them in a Holiday Card or use them as stocking stuffers. </br></br> </br>

- $14.99 - per account certificate</h2></center>

<center><br>
<%= image_tag("giftcertificatesml2.png", alt: "Gift Certificates")%>
</center></br></br>

<center></br>Click the Cart to Purchase</br>
<%= link_to image_tag("paypacrtsm.png", alt: "PayPal"),
              'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EBFTC7RA2CTPY' %></br>
             </center></br>
             
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/premium.erb
<title>Premium | Yourie</title>
<% provide(:title, "Premium") %>
<br />
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %>

  
</center>

<h1><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HMLCTAUKVD4EQ" title="PREMIUM ACCOUNT"><u>PREMIUM ACCOUNT</u></a></h1>
</br> 

<center><p>
<h3>Your Premium Account Includes:</h3><br />


<li>Unlimited Books</li>
<li>Unlimted Text Posts</li>
<li>12,500 Photo Posts</li>
<li>Unlimited Follow/Followed (Shares)</li>
<li>50 Gigibites Storage*</li>
<li>Vault Services</li>
</br>
<i>* Additional 50 GB storage and 12,500 photo posts can be purchased for $10 per year.</i>
<br /></center>

<center><%#= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %></br></center>








<center><h3>Just $24.99 Per Year!</h3></br>

</center>

<p>
<center><%= link_to image_tag("paypal.png", alt: "PayPal"),
              'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HMLCTAUKVD4EQ' %></center>
</br></br>
<center>We do not gather or store any personal or financial information other <br />than your email address 
and Yourie posts and images. <i>See "Terms of Use" below.</i><br /><br />
</center>


</p>
<br />
<center>Photos Stored Safely on Amazon's AWS Storage Services <%=image_tag("Amazon.png", alt: "Amazon")%>
<%= link_to image_tag("cloud.png", alt: "Cloud logo"),
              'https://yourie.herokuapp.com/' %></br></center><br />












<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/suggestions.erb
<% @user = current_user %>
</br>
<center><%=  image_tag("ylogomed.png", alt: "Yourie logo") %></center>

<h1>Suggestion Box</h1>

<!--<center>
<b>This is the first release of Yourie and we are working on several important </br>
features that will enhance your experience on the site including:</br></br>
 <li>Create chapters</li></br>
 <li>Insert and move posts up and down</li></br>
 <li>Advanced sharing features</li></br>
 <li>Post video and music files</li></b>
</br> 
</center>
<h1>Suggestion Box</h1>-->
<center><b>If you have any ideas or suggestions to improve the Yourie user experience we would love to hear from you.</br>
Just click the link below for the suggestion box form. </center></br>
</br>
<center><a href="http://www.usdigibrands.com/machform/view.php?id=12710" title="Yourie Suggestion & Comment Form"><b><font size="3" color="blue">Yourie Suggestion & Comment Form</font></b></a></center>
</br>
</br>
</br>
<center><b>Thank you for your thoughts!</center></br>