config/routes.rb
Rails.application.routes.draw do
  
  resources :manages
  resources :boxes
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'basic'    => 'static_pages#basic'
  get 'packages'    => 'static_pages#packages'
  get 'vault'    => 'static_pages#vault'
  get 'suggestions'    => 'static_pages#suggestions'
  get 'sample'    => 'static_pages#sample'
  get 'deleteaccount'    => 'static_pages#delete_account'
  get 'premium'    => 'static_pages#premium'
  get 'about'   => 'static_pages#about'
  get 'giftshop'   => 'static_pages#giftshop'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'invite'    => 'static_pages#invite'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boxes,          only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
  
  
  resources :relationships,       only: [:create, :destroy]
  resources :boxes do
  resources :microposts
    end
  
  resources :users do
  resources :microposts
    end
  resources :users do
  resources :boxes
    end
  resources :boxes do
  resources :users
    end
  resources :microposts do
  resources :users
    end
  resources :microposts do
  resources :boxes
    end
  
  resources :users,                only: [:edit, :create, :destroy]
  resources :boxes,                only: [:edit, :create, :destroy]
  resources :reverses
  resources :manages
  resources :microposts,          only: [:edit, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  
  def to_param
    Hashids.new("black napkins", 8).encode(id)
  end
  
  
  
  def FriendlyId
    "#{id} #{name}".parameterize
    extend FriendlyId
  friendly_id :name
  end
  has_many :boxes, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
   # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_columns(activated: true, activated_at:  Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), 
                   reset_sent_at: Time.zone.now)

  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  
  
  def index
     if current_user.admin 
     @users = User.where(activated: true).paginate(page: params[:page])
     
     else
     redirect_to root_url
     end
  end 
  
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def show
    id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    @user = User.find(id)
    @boxes = @user.boxes.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    @user = User.find(id)
  end

  def update
    id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    @user = User.find(id)
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    User.find(id).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def following
     id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    @title = "Following"
    @user  = User.find(id)
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
     id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
    @title = "Followers"
    @user  = User.find(id)
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      id = Hashids.new("black napkins", 8).decode(params[:id]).try(:first)
      @user = User.find(id)
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  </br>
  </br>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  </br>
  </br>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<h3>Users (<%= @users.count %>)</h3>
<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'signup_path') %>
<center><%= link_to image_tag("ylogomed.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></center></br>

 

<h1>Welcome To Yourie!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<br /><br />
<center>Your email and account information will never be sold to, or shared with, any third parties <i>See "Terms of Use" below.</i></center><br /><br />
<center>Photos Stored Safely on Amazon's AWS Storgae Services <%=image_tag("Amazon.png", alt: "Amazon")%></center><br />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!--users/show.html.erb with shared/boxes.html.erb -->
 <% params.inspect %>
<%  @user.id %>
 <center><!--Note: This is a MVP (Minimum Viable Product) prototype site for investor review only. Not all user functions and features are available.</center>--></center> 
<%  current_user.id %>
  <% if @user.id != current_user.id  %> 
    <div class="row">
      <aside class="col-md-4">
      <section class="user_info">
     
     
        
      <h1>
        <%= gravatar_for @user %> </h1>
        <%= @user.name %></br>
<div class="col-md-4">
   
   
  
    <% else %> 
    <div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %> </h1>
        <%= @user.name %></br>
        <%= link_to 'Create A New Book', new_box_path %>
       </section>
   
        <%= render 'shared/stats' %>
        
<%#= link_to "Demo",
              'https://yourie.herokuapp.com/users/pmvxzVQd' %></h1>
              
              <%#= link_to "Shared Demo 2",
              'https://yourie.herokuapp.com/users/bJVWBEer' %></h1>
              
              
<%#= link_to "About/Help",   about_path %></br></br>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account Settings
            </a>
            <ul class="dropdown-menu">
              
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Suggestions", suggestions_path %></li>
              <li><%= link_to "Cancel Your Account", deleteaccount_path %> </li>
              <li class="divider"></li>
              <li>
               </ul>
              
     
  <% end %>      
    
  </aside>
  <section>
  
        
        
  <% if @user.id != current_user.id  %> 
  
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <%  @boxes = @user.boxes(params[:id]) %>
    <% if @boxes.any? %>
    
      <h1> Bookshelf</h1> 
     <h6> (<%= @user.boxes.count %>) Books</h6>
      
    <% @boxes.each do |box| %>
     <% @book = box.book %>
     <h3>&middot; <%= link_to @book, box_path(box) %></h3>
            
    <% end %>  
    
  <% end %>
  
  <% else %> 
  
   <div class="col-md-8">
    
    <%  @boxes = @user.boxes(params[:id]).sort { |a,b| a.book <=> b.book } %>
    <% if @boxes.any? %>
    </br>
    </br>
    <center><b>
    <%= link_to "Share Your Yourie Album", invite_path, class: "btn btn-sm btn-primary" %></b></center>
      <h1> Bookshelf</h1> 
     <h6> Books: (<%= @user.boxes.count %>) </h6>
      
    <% @boxes.each do |box| %>
     <% @book = box.book %>
     <h3><%= link_to @book, box_path(box) %></h3>
        <%= link_to 'Show |', box %>
        <%= link_to 'Edit |', edit_box_path(box) %>
        <%= link_to 'Delete', box, method: :delete, data: { confirm: 'Are you sure?  This will delete the book and all content in the book ' } %>  
        
     <% end %> 
    <% end %>
    <center><%#= link_to "Delete Yourie Account", deleteaccount_path %></center>
    <% end %>
  </div>
  </section>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70798097-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <%= @user.name %>
      
      <span>Books: <%= @user.boxes.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>