config/routes.rb
Rails.application.routes.draw do
  
  resources :manages
  resources :boxes
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'basic'    => 'static_pages#basic'
  get 'packages'    => 'static_pages#packages'
  get 'vault'    => 'static_pages#vault'
  get 'suggestions'    => 'static_pages#suggestions'
  get 'sample'    => 'static_pages#sample'
  get 'deleteaccount'    => 'static_pages#delete_account'
  get 'premium'    => 'static_pages#premium'
  get 'about'   => 'static_pages#about'
  get 'giftshop'   => 'static_pages#giftshop'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'invite'    => 'static_pages#invite'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boxes,          only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
  
  
  resources :relationships,       only: [:create, :destroy]
  resources :boxes do
  resources :microposts
    end
  
  resources :users do
  resources :microposts
    end
  resources :users do
  resources :boxes
    end
  resources :boxes do
  resources :users
    end
  resources :microposts do
  resources :users
    end
  resources :microposts do
  resources :boxes
    end
  
  resources :users,                only: [:edit, :create, :destroy]
  resources :boxes,                only: [:edit, :create, :destroy]
  resources :reverses
  resources :manages
  resources :microposts,          only: [:edit, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/shared/_box_info.html.erb
<%  @boxes = @user.boxes(params[:id]) %>
    <% if @boxes.any? %>
      <h1> Bookshelf</h1> 
     <h6> (<%= @user.boxes.count %>) Books</h6>
      
    <% @boxes.each do |box| %>
     <% @book = box.book %>
     <h3><%= link_to @book, box_path(box) %></h3>
            
    <% end %>  
    <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%#= current_user.name %></br>
<%#= current_user.id %></br>
<%#= @boxes.user.id %></br>
<% if current_user.id == @boxes.user.id  %>
<%= form_for(Micropost.new, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose a new Yourie post here........." %>
    <%= f.hidden_field :boxes_id, :value => @boxes.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <span class="picture">
    
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpe' %>
  </span>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
<% else %>


<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 100), current_user %>
<h5><%= current_user.name %></h5>
<span><%= link_to " my books", current_user %></span>