config/routes.rb
Rails.application.routes.draw do
  
  resources :manages
  resources :boxes
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'basic'    => 'static_pages#basic'
  get 'packages'    => 'static_pages#packages'
  get 'vault'    => 'static_pages#vault'
  get 'suggestions'    => 'static_pages#suggestions'
  get 'sample'    => 'static_pages#sample'
  get 'deleteaccount'    => 'static_pages#delete_account'
  get 'premium'    => 'static_pages#premium'
  get 'about'   => 'static_pages#about'
  get 'giftshop'   => 'static_pages#giftshop'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'invite'    => 'static_pages#invite'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :boxes,          only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
  
  
  resources :relationships,       only: [:create, :destroy]
  resources :boxes do
  resources :microposts
    end
  
  resources :users do
  resources :microposts
    end
  resources :users do
  resources :boxes
    end
  resources :boxes do
  resources :users
    end
  resources :microposts do
  resources :users
    end
  resources :microposts do
  resources :boxes
    end
  
  resources :users,                only: [:edit, :create, :destroy]
  resources :boxes,                only: [:edit, :create, :destroy]
  resources :reverses
  resources :manages
  resources :microposts,          only: [:edit, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <small><%= link_to image_tag("ylogosmg.png", alt: "Yourie logo"),
              'https://yourie.herokuapp.com/' %></br>
    Personal Memories Organizer, Storage & Sharing  
    </br>Copyright © 2016 USDigiBrands, Inc.  <a href="https://yourie.herokuapp.com/"></a></br>
    Yourie&trade; & Yourie.com&trade; are trademarks of USDigiBrands, Inc.<br />
    All Rights Reserved. Patent Pending <br />
    *Amazon and the Amazon AWS Logo are properties of Amazon.com, Inc.  
    
    
  </small>
  <nav>
    <ul>
      <li><%#= link_to "Yourie Foundation",   youriepay_path %></li>
      <li><%= link_to "Privacy Policy", contact_path %></li>
      <li><%= link_to "Terms of Use", terms_path %></li>
      <li><%#= link_to "Photo Services", vault_path %></li>
      <li><%#= link_to "About/Help",   about_path %></li>
    </ul>
    
  </nav>
 </br>
 </br>
 </br>
<!--<ul></br></br> THIS IS NOT AN OFFER TO SELL OR A SOLICITATION OF ANY OFFER TO BUY ANY SECURITIES. OFFERS ARE MADE ONLY BY PRIVATE PLACEMENT MEMORANDUM OR OTHER OFFERING MATERIALS. TO OBTAIN FURTHER INFORMATION, YOU MUST COMPLETE OUR INVESTOR QUESTIONNAIRE AND MEET THE SUITABILITY STANDARDS REQUIRED BY LAW.

EXCEPT FOR HISTORICAL INFORMATION CONTAINED HEREIN, THIS DOCUMENT CONTAINS FORWARD-LOOKING STATEMENTS. SUCH FORWARD LOOKING STATEMENTS INVOLVE RISKS AND UNCERTAINTIES AND INCLUDE, BUT ARE NOT LIMITED TO, STATEMENTS REGARDING FUTURE EVENTS AND THE COMPANY'S PLANS AND EXPECTATIONS. THE COMPANY'S ACTUAL RESULTS MAY DIFFER MATERIALLY FROM SUCH STATEMENTS.

THE INCLUSION OF SUCH FORWARD-LOOKING INFORMATION SHOULD NOT BE REGARDED AS A REPRESENTATION BY THE COMPANY OR ANY OTHER PERSON THAT THE FUTURE EVENTS, PLANS OR EXPECTATIONS CONTEMPLATED BY THE COMPANY WILL BE ACHIEVED.</ul>
<center><%= link_to "", signup_path, class: "btn btn-lg btn-primary" %></center></br>
</footer>-->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("picsmy.png", alt: "Yourie logo"), current_user, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-center">
        <% if logged_in? %>
        <li><%= link_to "Home",   current_user %></li>
        
        <% else %>
        <li><%= link_to "Home",   root_path %></li>
        <% end %>
        
        
        <% if logged_in? %>
         <li><%= link_to "Log out", logout_path, method: "delete" %></li>
         <li><%#= link_to "*Yourie is Crowd Funded",   youriepay_path %></li>
         <li><%= link_to "Help",   help_path %></li>
         <li><%#= link_to "Sample 'Books'",
              'https://yourie.herokuapp.com/users/pmvxzVQd' %></li>
         <li><%#= link_to "Suggestions", suggestions_path %></li>
         <li><%= link_to "Gift Shop", giftshop_path %></li>
         <li><%= link_to "Services", vault_path %></li>
          <% if current_user.admin %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          
          
            </ul>
          </li>
        <% else %>
          
          <li><%= link_to "Log in", login_path %></li>
          <li><%#= link_to "The Yourie Story",   sample_path %></li>
          <li><%= link_to "Sample",   about_path %></li>
          <li><%= link_to "Gift Shop", giftshop_path %></li>
          <li><%= link_to "Services", vault_path %></li>
          
          <li><%#= link_to "*Yourie is Crowd Funded",   youriepay_path %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript" src="https://ss.sharethis.com/loader.js"></script>
    <meta name="google-site-verification" content="BhwKfknu7jpXeG7pz6bnvcqgdGY1Y23jJiITyfh0Cb4" />
    <title><%= full_title(yield(:title)) %></title>
    <meta name='description'content='<%= yield_meta_tag(:description, 'Yourie - A cloud based website where you can organize, store and share your memorable life experiences with family and friends through photos and text') %>' />
    <meta name='keywords'content='<%= yield_meta_tag(:keywords, 'picture albums, photo albums, phoyobook, photo organizers, scrapbooking, scrapbook, memory books, memorybooks, photobooks, photobooks online') %>' />
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
 
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  
</html>
<script type="text/javascript">stLight.options({publisher: "c14ff29b-ab4b-400b-8636-5feeac74864c", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>



<!-- Yourie 1 -->